"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LAYOUT_CHANGE = "LAYOUT_CHANGE";
exports.APP_STARTED = "APP_STARTED";
exports.CLEAR_CACHE_DATA = "CLEAR_CACHE_DATA";
exports.START_EDIT_CART_ITEM = "START_EDIT_CART_ITEM";
exports.FINISH_EDIT_CART_ITEM = "FINISH_EDIT_CART_ITEM";
exports.START_ADD_CART_ITEM = "START_ADD_CART_ITEM";
exports.FINISH_ADD_CART_ITEM = "FINISH_ADD_CART_ITEM";
exports.START_REMOVE_CART_ITEMS = "START_REMOVE_CART_ITEMS";
exports.FINISH_REMOVE_CART_ITEMS = "FINISH_REMOVE_CART_ITEMS";
exports.START_FETCH_CART_LIST = "START_FETCH_CART_LIST"; // 获取
exports.FINISH_FETCH_CART_LIST = "FINISH_FETCH_CART_LIST";
exports.LOCATION_UPDATE = "LOCATION_UPDATE"; // 更新地址
// 切换门店
exports.CHANGE_SHOP = "CHANGE_SHOP";
/**
 * 高德地图API通过经纬度获取小区地址信息
 */
exports.ADD_REGEO_DATA = "ADD_REGEO_DATA";
exports.START_SEARCHING_REGEO_DATA = "SEARCHING_REGEO_DATA";
exports.FINISH_SEARCHING_REGEO_DATA = "FINISH_SEARCHING_REGEO_DATA";
//定位
exports.START_GPS_LOCATION = "START_GPS_LOCATION";
exports.FINISH_GPS_LOCATION = "FINISH_GPS_LOCATION";
//////////////////////////////////////////////////////
exports.UI_SET_ADDR = "UI_SET_ADDR";
exports.UI_UPDATE_ADDR = "UI_UPDATE_ADDR";
exports.UI_CHANGE_ADDR_LOCATION = "UI_CHANGE_ADDR_LOCATION";
exports.UI_CLEAR_ADDR_LOCATION = "UI_CLEAR_ADDR_LOCATION";
exports.UI_SET_AMAP_TYPE = "UI_SET_AMAP_TYPE";
exports.UI_CARTS_SELECT = "UI_CARTS_SELECT";
exports.UI_CARTS_CANCEL_SELECT = "UI_CARTS_CANCEL_SELECT";
exports.UI_CARTS_CLEAR_SELECT = "UI_CARTS_CLEAR_SELECT";
exports.UI_SUBMIT_ORDER_ITEMS = "UI_SUBMIT_ORDER_ITEMS";
exports.UI_SUBMIT_ORDER_ADDR = "UI_SUBMIT_ORDER_ADDR";
exports.UI_SUBMIT_ORDER_TIME = "UI_SUBMIT_ORDER_TIME";
exports.UI_SUBMIT_ORDER_MEMO = "UI_SUBMIT_ORDER_MEMO";
exports.UI_SUBMIT_ORDER_COUPON = "UI_SUBMIT_ORDER_COUPON";
exports.UI_MY_ORDER_CAHNGE_TAB = "UI_MY_ORDER_CAHNGE_TAB";
////////////////////////////////////////////////////
//收货地址
//添加
exports.START_ADD_ADDR = "START_ADD_ADDR";
exports.FINISH_ADD_ADDR = "FINISH_ADD_ADDR";
//删除
exports.START_DELETE_ADDR = "START_DELETE_ADDR";
exports.FINISH_DELETE_ADDR = "FINISH_DELETE_ADDR";
//修改
exports.START_EDIT_ADDR = "START_EDIT_ADDR";
exports.FINISH_EDIT_ADDR = "FINISH_EDIT_ADDR";
//获取
exports.START_FETCH_ADDRLIST = "START_FETCH_ADDRLIST";
exports.FINISH_FETCH_ADDRLIST = "FINISH_FETCH_ADDRLIST";
////////////////////////////////////////////////////
// 正在进行http请求
exports.ACTION_HTTP_REQUESTING = "ACTION_HTTP_REQUESTING";
// http请求超时的通用处理
exports.ACTION_HTTP_TIMEOUT = "ACTION_HTTP_TIMEOUT";
// http错误处理
exports.ACTION_HTTP_ERROR = "ACTION_HTTP_ERROR";
// http请求结束
exports.ACTION_HTTP_REQUEST_FINISH = "ACTION_HTTP_REQUEST_FINISH";
//////////////////////////////////////////////////////////////////////
//订单
exports.START_NEW_ORDER = "START_NEW_ORDER";
exports.FINISH_NEW_ORDER = "FINISH_NEW_ORDER";
exports.START_FETCH_ORDERLIST = "START_FETCH_ORDERLIST";
exports.FINISH_FETCH_ORDERLIST = "FINISH_FETCH_ORDERLIST";
//接单
exports.START_TAKE_ORDER = "START_TAKE_ORDER";
exports.FINISH_TAKE_ORDER = "FINISH_TAKE_ORDER";
//完成订单
exports.START_FINISH_ORDER = "START_FINISH_ORDER";
exports.FINISH_FINISH_ORDER = "FINISH_FINISH_ORDER";
exports.START_DELETE_ORDER = "START_DELETE_ORDER";
exports.FINISH_DELETE_ORDER = "FINISH_DELETE_ORDER";
exports.START_CANCEL_ORDER = "START_CANCEL_ORDER";
exports.FINISH_CANCEL_ORDER = "FINISH_CANCEL_ORDER";
exports.START_BUY_AGAIN = "START_BUY_AGAIN";
exports.FINISH_BUY_AGAIN = "FINISH_BUY_AGAIN";
//////////////////////////////////////////////////////////////////////
//首页
//topbanner
exports.START_FETCH_TOPBANNER = "START_FETCH_TOPBANNER";
exports.FINISH_FETCH_TOPBANNER = "FINISH_FETCH_TOPBANNER";
//activeItem
exports.START_FETCH_ACTIVEITEM = "START_FETCH_ACTIVEITEM";
exports.FINISH_FETCH_ACTIVEITEM = "FINISH_FETCH_ACTIVEITEM";
//Category
exports.START_FETCH_CATEGORY = "START_FETCH_CATEGORY";
exports.FINISH_FETCH_CATEGORY = "FINISH_FETCH_CATEGORY";
//Coupon
exports.START_FETCH_COUPON = "START_FETCH_COUPON";
exports.FINISH_FETCH_COUPON = "FINISH_FETCH_COUPON";
exports.SELECT_COUPON = "SELECT_COUPON";
//My
exports.START_FETCH_MY = "START_FETCH_MY";
exports.FINISH_FETCH_MY = "FINISH_FETCH_MY";
//ItemDynamic
exports.START_FETCH_ITEMDYNAMIC = "START_FETCH_ITEMDYNAMIC";
exports.FINISH_FETCH_ITEMDYNAMIC = "FINISH_FETCH_ITEMDYNAMIC";
//Search
exports.START_FETCH_SEARCH = "START_FETCH_SEARCH";
exports.CLEAR_SEARCH = "CLEAR_SEARCH";
//支付
exports.USER_PAY_ALI = "USER_PAY_ALI";
exports.USER_PAY_WECHAT = "USER_PAY_WECHAT";
exports.USER_PAY_DAOFU = "USER_PAY_DAOFU";
//退出登录
exports.USER_LOGIN_WECHAT = "USER_LOGIN_WECHAT";
exports.USER_LOG_OUT = "USER_LOG_OUT";
exports.START_USER_LOGIN = "START_USER_LOGIN";
exports.FINISH_USER_LOGIN = "FINISH_USER_LOGIN";
exports.START_USER_GET_VCODE = "START_USER_GET_VCODE";
exports.FINISH_USER_GET_VCODE = "FINISH_USER_GET_VCODE";
exports.USER_ACTIVE_LOG_OUT = "USER_ACTIVE_LOG_OUT";
//意见反馈
exports.START_FEED_BACK = "START_FEED_BACK";
exports.FINISH_FEED_BACK = "FINISH_FEED_BACK";
// checkauth
exports.START_CHECK_AUTH = "START_CHECK_AUTH";
exports.FINISH_CHECK_AUTH = "FINISH_CHECK_AUTH";
//# sourceMappingURL=ActionTypes.js.map