"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const action_1 = require("../common/utils/action");
const ActionTypes = require("../constants/ActionTypes");
exports.changeLayout = (layout) => (action_1.createAction(ActionTypes.LAYOUT_CHANGE, layout));
exports.startApp = () => (action_1.createAction(ActionTypes.APP_STARTED));
exports.clearCacheData = () => (action_1.createAction(ActionTypes.CLEAR_CACHE_DATA));
exports.changeAddrLocation = (location) => (action_1.createAction(ActionTypes.UI_CHANGE_ADDR_LOCATION, location));
exports.setUiAddr = (add, addr) => (action_1.createAction(ActionTypes.UI_SET_ADDR, { add, addr }));
exports.updateUiAddr = (addr) => (action_1.createAction(ActionTypes.UI_UPDATE_ADDR, addr));
exports.setAMapOpType = (type) => (action_1.createAction(ActionTypes.UI_SET_AMAP_TYPE, type));
exports.setCouponSelect = (id) => (action_1.createAction(ActionTypes.SELECT_COUPON, id));
exports.logout = () => (action_1.createAction(ActionTypes.USER_ACTIVE_LOG_OUT));
exports.selectCartsItems = (ids) => (action_1.createAction(ActionTypes.UI_CARTS_SELECT, ids));
exports.unSelectCartsItems = (ids) => (action_1.createAction(ActionTypes.UI_CARTS_CANCEL_SELECT, ids));
exports.clearSelectedCartsItems = () => (action_1.createAction(ActionTypes.UI_CARTS_CLEAR_SELECT));
exports.setSubmitOrderItems = (items) => (action_1.createAction(ActionTypes.UI_SUBMIT_ORDER_ITEMS, items));
exports.setSubmitOrderAddr = (addr) => (action_1.createAction(ActionTypes.UI_SUBMIT_ORDER_ADDR, addr));
exports.setSubmitOrderTime = (time) => (action_1.createAction(ActionTypes.UI_SUBMIT_ORDER_TIME, time));
exports.setSubmitOrderMemo = (memo) => (action_1.createAction(ActionTypes.UI_SUBMIT_ORDER_MEMO, memo));
exports.setSubmitOrderCoupon = (memo) => (action_1.createAction(ActionTypes.UI_SUBMIT_ORDER_COUPON, memo));
exports.changeMyOrderTab = (page) => (action_1.createAction(ActionTypes.UI_MY_ORDER_CAHNGE_TAB, page));
exports.startAliPay = (order) => (action_1.createAction(ActionTypes.USER_PAY_ALI, order));
exports.startWeChatPay = (order) => (action_1.createAction(ActionTypes.USER_PAY_WECHAT, order));
exports.startDaoFuPay = (order) => (action_1.createAction(ActionTypes.USER_PAY_DAOFU, order));
//# sourceMappingURL=ui.js.map